# Diccionario para estandarizar nombres de detalles
DETAIL_STANDARDIZATION = {
    'Fruliftsland': 'Friluftsland',
    'HM': 'HyM',
    'Fotex': 'Foetex',
    'Flying Tyger': 'Flying Tiger',
    'Uniqlo': 'UNIQLO',
    'Visa Cashbacj Restaurante': 'Visa Cashback Restaurante',
    'Holms Cafñ & Br': 'Holms',
    'Boligfonden DTU': 'BDTU',
    'Hym Home': 'HyM Home',
    '365 Lyngby': 'Coop365',
    'Ikea': 'IKEA',
    'Groed 2': 'Groed',
    'Politikens Boghal (libro)': 'Politikens Boghal',
    'Illum (Muji)': 'Illum',
    'Nortec System': 'e-vaskeri',
    'Netto DTU': 'Netto',
    'Supermarket 365': 'Coop365',
    'Føtex': "Foetex",
    'Jysk': 'JYSK',
    'HYM home': 'HyM Home',
    'Soestrene': 'Soestrene Grene',
    'Meny': 'MENY',
    'GitHub': 'Github',
    'Yousee': 'YouSee',
    'E-vaskery': 'e-vaskeri',
    '7eleven': '7-eleven',
    'Sostrene Grene': 'Soestrene Grene',
    'Apple': 'iCloud',
    'Fri bikeshop': 'Fri Bikeshop',
    'Viaje': 'Gastos Viaje Alemania',
    'Café DTU': 'DTU Cafe',
    'DTU Food App': 'DTU Cafe',
    'DTU 101 Cafe': 'DTU Cafe',
    'DTU 358 Cafe': 'DTU Cafe',
    'DTU 202 Lunch': 'DTU Cafe',
    'DTU 306 Café': 'DTU Cafe',
    'Caffeen': 'KU Cafe',
}

CATEGORY_STANDARDIZATION = {
    'Viaje': 'Viajes',
    'Educación': 'Estudios',
    'Regalo': 'Regalos',
    'Cuidado Personal': 'Cuidado personal',
}

DETAIL_TO_SUBCATEGORY = {
    "Comida": {
        'Cafe aeropuerto': 'Cafe',
        'KU Cafe': 'Cafe universidad',
        'DTU Cafe': 'Cafe universidad',
        'Hotdog danes': 'Snacks',
        'Starbucks': 'Cafe',
        'Superbrugsen': 'Supermercado',
        'Joe The Juice': 'Cafe',
        'Buka': 'Cafe',
        'Mad Kaffe Lyngby': 'Restaurante',
        "Foetex": "Supermercado",
        "Netto": "Supermercado",
        "Coop365": "Supermercado",
        'Un Mercato': 'Restaurante',
        'Wolt': 'Restaurante',
        'REWE': 'Supermercado',
        'Espresso House': 'Cafe',
        'MENY': 'Supermercado',
        'Café Schlosser': 'Cafe',
        'Grimminger': 'Cafe',
        'Holms': 'Restaurante',
        '7-eleven': 'Snacks',
        'SMAG APS': 'Restaurante',
        'Sushi Lovers': 'Restaurante',
        'Aps kbus': 'Restaurante',
        'Subway': 'Restaurante',
        'Elis': 'Snacks',
        'Thilo Von': 'Snacks',
        'Gasoline Grill Tivoli': 'Restaurante',
        'Emmerys': 'Cafe',
        'Fresh Market': 'Restaurante',
        'IKEA Restaurant': 'Restaurante',
        'Foreningen': 'Snacks',
        'Circle K': 'Snacks',
        'El Meson': 'Restaurante',
        'Capi Bara': 'Restaurante',
        'Groed': 'Restaurante',
        'Kaffestuen': 'Cafe',
        'McDonalds': 'Restaurante',
        'Naruto Sushi': 'Restaurante',
        'Park Kiosk': 'Snacks',
        'Parma y Pasta': 'Restaurante',
        'Patisserie': 'Cafe',
        'Q8 Service': 'Snacks',
        'Uber eats': 'Restaurante',
    },

}
