# Diccionario para estandarizar nombres de detalles
DETAIL_STANDARDIZATION = {
    'Fruliftsland': 'Friluftsland',
    'HM': 'HyM',
    'Fotex': 'Foetex',
    'Flying Tyger': 'Flying Tiger',
    'Uniqlo': 'UNIQLO',
    'Visa Cashbacj Restaurante': 'Visa Cashback Restaurante',
    'Holms Cafñ & Br': 'Holms',
    'Boligfonden DTU': 'BDTU',
    'Hym Home': 'HyM Home',
    '365 Lyngby': 'Coop365',
    'Ikea': 'IKEA',
    'Groed 2': 'Groed',
    'Politikens Boghal (libro)': 'Politikens Boghal',
    'Illum (Muji)': 'Illum',
    'Nortec System': 'e-vaskeri',
    'Netto DTU': 'Netto',
    'Supermarket 365': 'Coop365',
    'Føtex': "Foetex",
    'Jysk': 'JYSK',
    'HYM home': 'HyM Home',
    'Soestrene': 'Soestrene Grene',
    'Meny': 'MENY',
    'GitHub': 'Github',
    'Yousee': 'YouSee',
    'E-vaskery': 'e-vaskeri',
    '7eleven': '7-eleven',
    'Sostrene Grene': 'Soestrene Grene',
    'Apple': 'iCloud',
    'Fri bikeshop': 'Fri Bikeshop'
}

CATEGORY_STANDARDIZATION = {
    'Viaje': 'Viajes',
    'Educación': 'Estudios'
}

DETAIL_TO_SUBCATEGORY = {
    'DTU 101 Cafe': 'DTU Cafe',
    'Caffeen': 'KU Cafe',
    'Sushi Lovers': 'Salida',
    'Hotdog danes': 'Salida',
    'Studenterhuset': 'Salida',
    'Bastard Cafe': 'Salida',
    'Fresh Market': 'Salida',
    'DTU 358 Cafe': 'DTU Cafe',
    'DTU 202 Lunch': 'DTU Cafe',
    'DTU 306 Café': 'DTU Cafe',
    'Starbucks': 'Cafe',
    'Superbrugsen': 'Supermercado',
    'Joe The Juice': 'Cafe',
    'Buka': 'Cafe',
    'Mad Kaffe Lyngby': 'Cafe',
    "Foetex": "Supermercado",
    "Netto": "Supermercado",
    "Coop 365": "Supermercado",
    'Un Mercato': 'Salida',
    'Subway': 'Salida',
    'Wolt': 'Salida',
    'Tivoli': 'Salida',
    'REWE': 'Supermercado',
    'Espresso House': 'Cafe',
    'MENY': 'Supermercado',
    'Café Schlosser': 'Cafe',
    'Grimminger': 'Cafe',
    'Holms': 'Cafe',
}
